export type NodeType = 'folder' | 'item' | 'expense';

export interface FolderNode {
  id: string;
  name: string;
  type: 'folder' | 'item';
  parentId: string | null;
  isAutoGenerated?: boolean; // For auto-created subfolders of items
  createdAt: Date;
}

export interface Expense {
  id: string;
  folderId: string;
  category: string;
  value: number;
  date: Date;
  description: string;
  createdAt: Date;
}

export interface TreeNode extends FolderNode {
  children: TreeNode[];
  expenses: Expense[];
}

export const EXPENSE_CATEGORIES = [
  'Aquisição',
  'Manutenção',
  'Documentos',
  'Upgrades',
  'Reparo',
  'Seguro',
  'Imposto',
  'Outros',
] as const;

export const ITEM_SUBFOLDERS = ['Aquisição', 'Manutenção', 'Documentos', 'Upgrades'] as const;

export interface PathSegment {
  id: string;
  name: string;
}
