import { useState, useMemo } from 'react';
import { usePatrimonyStore, getSelectedFolder, getTotalExpenses, getFolderExpenses } from '@/store/patrimonyStore';
import { Breadcrumb } from '@/components/Breadcrumb';
import { ExpenseList } from '@/components/ExpenseList';
import { CreateDialogs } from '@/components/CreateDialogs';
import { Button } from '@/components/ui/button';
import { 
  FolderPlus, 
  Package, 
  Receipt, 
  Calculator, 
  List, 
  Folder,
  Building2
} from 'lucide-react';

const formatCurrency = (value: number) => {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
  }).format(value);
};

export function DetailsPanel() {
  const selectedFolderId = usePatrimonyStore((s) => s.selectedFolderId);
  const folders = usePatrimonyStore((s) => s.folders);
  const expenses = usePatrimonyStore((s) => s.expenses);

  const [openDialog, setOpenDialog] = useState<'folder' | 'item' | 'expense' | null>(null);
  const [showTotal, setShowTotal] = useState(false);
  const [showExpenses, setShowExpenses] = useState(false);

  const selectedFolder = useMemo(() => getSelectedFolder(folders, selectedFolderId), [folders, selectedFolderId]);
  
  const total = useMemo(() => {
    if (!selectedFolderId) return 0;
    return getTotalExpenses(folders, expenses, selectedFolderId);
  }, [folders, expenses, selectedFolderId]);
  
  const folderExpenses = useMemo(() => {
    if (!selectedFolderId) return [];
    return getFolderExpenses(folders, expenses, selectedFolderId, true);
  }, [folders, expenses, selectedFolderId]);

  if (!selectedFolder) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-8 text-center bg-background">
        <div className="w-16 h-16 rounded-2xl bg-secondary flex items-center justify-center mb-4">
          <Building2 className="h-8 w-8 text-muted-foreground" />
        </div>
        <h3 className="text-lg font-medium text-foreground mb-2">
          Selecione uma pasta
        </h3>
        <p className="text-sm text-muted-foreground max-w-xs">
          Escolha uma empresa ou pasta na estrutura ao lado para ver detalhes e gerenciar despesas.
        </p>
      </div>
    );
  }

  const getIcon = () => {
    if (selectedFolder.type === 'item') {
      return <Package className="h-5 w-5 text-item-icon" />;
    }
    if (selectedFolder.parentId === null) {
      return <Building2 className="h-5 w-5 text-folder-icon" />;
    }
    return <Folder className="h-5 w-5 text-folder-icon" />;
  };

  return (
    <div className="h-full flex flex-col bg-background">
      {/* Header */}
      <div className="p-4 border-b border-border">
        <Breadcrumb />
        <div className="flex items-center gap-3 mt-3">
          {getIcon()}
          <div>
            <h2 className="text-lg font-semibold text-foreground">{selectedFolder.name}</h2>
            <p className="text-xs text-muted-foreground">
              {selectedFolder.type === 'item' ? 'Item patrimonial' : 'Pasta'}
              {selectedFolder.isAutoGenerated && ' • Automática'}
            </p>
          </div>
        </div>
      </div>

      {/* Actions */}
      <div className="p-4 border-b border-border">
        <div className="flex flex-wrap gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setOpenDialog('folder')}
            className="gap-2"
          >
            <FolderPlus className="h-4 w-4" />
            Nova Pasta
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => setOpenDialog('item')}
            className="gap-2"
          >
            <Package className="h-4 w-4" />
            Novo Item
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => setOpenDialog('expense')}
            className="gap-2"
          >
            <Receipt className="h-4 w-4" />
            Nova Despesa
          </Button>
        </div>
        
        <div className="flex flex-wrap gap-2 mt-3">
          <Button
            variant={showTotal ? 'default' : 'secondary'}
            size="sm"
            onClick={() => { setShowTotal(!showTotal); setShowExpenses(false); }}
            className="gap-2"
          >
            <Calculator className="h-4 w-4" />
            Ver Total
          </Button>
          <Button
            variant={showExpenses ? 'default' : 'secondary'}
            size="sm"
            onClick={() => { setShowExpenses(!showExpenses); setShowTotal(false); }}
            className="gap-2"
          >
            <List className="h-4 w-4" />
            Listar Despesas
          </Button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-4">
        {showTotal && (
          <div className="animate-fade-in">
            <div className="p-6 rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 border border-primary/20">
              <p className="text-sm text-muted-foreground mb-1">Total de despesas</p>
              <p className="text-3xl font-bold text-gradient">
                {formatCurrency(total)}
              </p>
              <p className="text-xs text-muted-foreground mt-2">
                Inclui {folderExpenses.length} despesa{folderExpenses.length !== 1 ? 's' : ''} (todas as subpastas)
              </p>
            </div>
          </div>
        )}

        {showExpenses && (
          <div className="animate-fade-in">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-medium text-foreground">
                Despesas ({folderExpenses.length})
              </h3>
              <p className="text-sm text-muted-foreground">
                Total: <span className="text-foreground font-medium">{formatCurrency(total)}</span>
              </p>
            </div>
            <ExpenseList expenses={folderExpenses} />
          </div>
        )}

        {!showTotal && !showExpenses && (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <div className="w-12 h-12 rounded-xl bg-secondary flex items-center justify-center mb-3">
              <Calculator className="h-6 w-6 text-muted-foreground" />
            </div>
            <p className="text-sm text-muted-foreground">
              Use os botões acima para ver o total ou listar despesas
            </p>
          </div>
        )}
      </div>

      <CreateDialogs openDialog={openDialog} onClose={() => setOpenDialog(null)} />
    </div>
  );
}
