import { ChevronRight, ChevronDown, Folder, FolderOpen, Package, FileText } from 'lucide-react';
import { usePatrimonyStore } from '@/store/patrimonyStore';
import { TreeNode } from '@/types/patrimony';
import { cn } from '@/lib/utils';

interface TreeItemProps {
  node: TreeNode;
  level: number;
}

function TreeItem({ node, level }: TreeItemProps) {
  const selectedFolderId = usePatrimonyStore((s) => s.selectedFolderId);
  const expandedIds = usePatrimonyStore((s) => s.expandedIds);
  const selectFolder = usePatrimonyStore((s) => s.selectFolder);
  const toggleExpand = usePatrimonyStore((s) => s.toggleExpand);

  const isSelected = selectedFolderId === node.id;
  const isExpanded = expandedIds.has(node.id);
  const hasChildren = node.children.length > 0;

  const handleClick = () => {
    selectFolder(node.id);
    if (hasChildren) {
      toggleExpand(node.id);
    }
  };

  const getIcon = () => {
    if (node.type === 'item') {
      return <Package className="h-4 w-4 text-item-icon" />;
    }
    if (node.isAutoGenerated) {
      return <FileText className="h-4 w-4 text-muted-foreground" />;
    }
    if (isExpanded && hasChildren) {
      return <FolderOpen className="h-4 w-4 text-folder-icon" />;
    }
    return <Folder className="h-4 w-4 text-folder-icon" />;
  };

  return (
    <div className="animate-fade-in">
      <button
        onClick={handleClick}
        className={cn(
          'w-full flex items-center gap-1 py-1.5 px-2 rounded-md text-left transition-all duration-150 group',
          'hover:bg-secondary/60',
          isSelected && 'bg-secondary text-foreground'
        )}
        style={{ paddingLeft: `${level * 16 + 8}px` }}
      >
        <span className="w-4 h-4 flex items-center justify-center shrink-0">
          {hasChildren ? (
            isExpanded ? (
              <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
            ) : (
              <ChevronRight className="h-3.5 w-3.5 text-muted-foreground" />
            )
          ) : null}
        </span>
        {getIcon()}
        <span className={cn(
          'text-sm truncate ml-1.5',
          node.type === 'item' ? 'font-medium' : 'font-normal',
          node.isAutoGenerated && 'text-muted-foreground'
        )}>
          {node.name}
        </span>
        {node.expenses.length > 0 && (
          <span className="ml-auto text-xs text-muted-foreground bg-muted px-1.5 py-0.5 rounded">
            {node.expenses.length}
          </span>
        )}
      </button>
      
      {isExpanded && hasChildren && (
        <div className="relative">
          <div 
            className="absolute left-0 top-0 bottom-0 tree-connector"
            style={{ marginLeft: `${level * 16 + 20}px` }}
          />
          {node.children.map((child) => (
            <TreeItem key={child.id} node={child} level={level + 1} />
          ))}
        </div>
      )}
    </div>
  );
}

export function FolderTree() {
  const tree = usePatrimonyStore((s) => s.getTree());
  const expandAll = usePatrimonyStore((s) => s.expandAll);
  const collapseAll = usePatrimonyStore((s) => s.collapseAll);

  return (
    <div className="h-full flex flex-col bg-card border-r border-border">
      <div className="p-4 border-b border-border flex items-center justify-between">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          Estrutura
        </h2>
        <div className="flex gap-1">
          <button
            onClick={expandAll}
            className="p-1.5 rounded hover:bg-secondary text-muted-foreground hover:text-foreground transition-colors"
            title="Expandir tudo"
          >
            <ChevronDown className="h-3.5 w-3.5" />
          </button>
          <button
            onClick={collapseAll}
            className="p-1.5 rounded hover:bg-secondary text-muted-foreground hover:text-foreground transition-colors"
            title="Recolher tudo"
          >
            <ChevronRight className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>
      
      <div className="flex-1 overflow-y-auto p-2">
        {tree.length > 0 ? (
          tree.map((node) => (
            <TreeItem key={node.id} node={node} level={0} />
          ))
        ) : (
          <div className="px-3 py-8 text-center">
            <Folder className="h-8 w-8 text-muted-foreground/50 mx-auto mb-2" />
            <p className="text-sm text-muted-foreground">
              Nenhuma pasta criada
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
